### ISSUE TITLE
Can it support a large C++ project？

### ISSUE THREAD

**Issue by 263868161** [bkryza/clang-uml#121]
When I tried to apply it to a large C++ project, because the directory tree was more responsible, I found many problems, such as“file not found”，How to solve or is there any example?，Thank you!

**Comment by bkryza** [comment]
@263868161 Hi, the size of the project shouldn't matter.

Can you share more details about your environment:
* operating system
* clang-uml version
* .clang-uml configuration file
* directory structure of your project
* excerpt from your compile_commands.json
* example errors you are getting

Some hints:
* start small - specify `glob` section so that it points to only a single translation unit (single cpp file)
* make sure `std` namespace is excluded from diagrams either by specifying `include` for a specific namespace in your project or explicitly defining `exclude` for `std`
* make sure your project actually compiles on your system

Some examples for larger projects are here: https://github.com/bkryza/clang-uml-examples

**Comment by 263868161** [comment]
“https://github.com/bkryza/clang-uml-examples“ How to get the C++ source code？

**Comment by bkryza** [comment]
@263868161 not sure what you mean? If you mean how to get the source codes for the projects reference in `clang-uml-examples` just run make and it it will clone them from GitHub, e.g.: 
https://github.com/bkryza/clang-uml-examples/blob/master/poco/Makefile#L8
