### ISSUE TITLE
Tedious and hard to use in professional environement

### ISSUE THREAD

**Issue by phil1234567891011** [bkryza/clang-uml#124]
Hi,

I really worked my a.. off to have it generate diagrams, the example config had to many options to work
yet I did not grasp it is actually generating .puml files in the end

so I realized it relied on some obscure plantuml library. there does not seem to be any executable but a .jar file

in the end, I cannot really use it on a VM that has strict group policies
also I really had to narrow down the code I was analyzing with clang-uml.exe or I had some errors and the diagram was not generated

well, maybe these would need improvements

**Comment by bkryza** [comment]
@phil1234567891011 

> I really worked my a.. off to have it generate diagrams, the example config had to many options to work

Granted, the usability and user experience are not yet my top priority as the focus is on handling as much of C++ as possible. The idea is that once you have proper configuration files you can regenerate the diagrams automatically as your code evolves.

>yet I did not grasp it is actually generating .puml files in the end so I realized it relied on some obscure plantuml library. there does not seem to be any executable but a .jar file

Yes, PlantUML is a Java application (for better or worse) - however I would hardly call it obscure: https://github.com/plantuml/plantuml . Also it is mention in the main README and in Quick start section...

> in the end, I cannot really use it on a VM that has strict group policies

Is this specific to some concrete hypervisor - I actually use `clang-uml` and `PlantUML` on Windows 10 in a VirtualBox VM and never had to deal with any policies...

> also I really had to narrow down the code I was analyzing with clang-uml.exe or I had some errors and the diagram was not generated

Can you share any specific errors? Assuming your code compiles correctly, the errors usually fall into 2 categories:
* Clang cannot find some header due to bad include paths in compile_commands.json (see for instance: https://github.com/bkryza/clang-uml/blob/master/docs/troubleshooting.md#fatal-error-stddefh-file-not-found)
* Bugs in `clang-uml` - in this case it would be useful for me if you could rerun `clang-uml` in verbose mode (`-vvv`) and paste the end of the output before the errors or crash...

> well, maybe these would need improvements

Can you describe how you would improve the UX of this tool to better suit your workflow?

**Comment by phil1234567891011** [comment]
yeah a header was missing, it's not my code
do you have any alternative to plantuml ?

I tried using 

`clang++ -S -emit-llvm main1.cpp -o - | opt -analyze -dot-callgraph`

but opt is nowhere to be found on windows nor in llvm distribution

**Comment by bkryza** [comment]
`clang-uml` only generates diagrams in PlantUML format at the moment. However if you just want to generate few diagrams, you can use one of the online PlantUML services, e.g.:

https://www.planttext.com/

and just paste the contents of the generated `*.puml` file and download the diagram...
