### ISSUE TITLE
Any way to use absolute paths for glob?

### ISSUE THREAD

**Issue by ACGNnsj** [bkryza/clang-uml#229]
It seems that glob option will just concact the paths directly anyway. It's  stupidish if I have to move the project files to be analyzed.

**Comment by ACGNnsj** [comment]
I finally find I have to move the tool and config files around instead of the project to make the glob pattern match the paths in 'compile_commands.json'. That's funny.

**Comment by bkryza** [comment]
@ACGNnsj Can you share more details?
- path to your project sources
- location of `.clang-uml` file
- contents of `.clang-uml` file
- errors you're getting

In general the idea is that you keep `.clang-uml` with your project so that paths are relative so that you can move the configuration between different environments and paths will be valid anywhere.

If your use case is different somehow I'd love to know what is it.

Also, you can tell `clang-uml` to treat all paths as relative to $PWD instead of location of `.clang-uml`:
```
--paths-relative-to-pwd     If true, all paths in configuration files are relative to the $PWD instead of actual location of `.clang-uml` file.
```
