### ISSUE TITLE
clang-uml cannot find libary files

### ISSUE THREAD

**Issue by himalalps** [bkryza/clang-uml#249]
I am using clang-uml on Windows 11, but it reports error that cannot find `<stdexcept>` file.
The `<stdexcept>` file is in folder `D:\llvm-mingw\include\c++\v1\`, how can I fix the error?

```
Generating diagram 1_MiniDraw
D:\xxx\src\main.cpp:1:10: fatal error:
      'stdexcept' file not found
    1 | #include <stdexcept>
      |          ^~~~~~~~~~~
1 error generated.
Error while processing D:\xxx\src\main.cpp.
```

**Comment by bkryza** [comment]
@himalalps It seems that for some reason your compile_commands.json does not contain valid include paths. You can try to inject the compilation flag on the command line, e.g.:

```console
clang-uml --add-compile-flag "-I D:/llvm-mingw/include/c++/v1"
```

or add the following to `.clang-uml` config somewhere at the top:

```yaml
add_compile_flags:
  - "-I D:/llvm-mingw/include/c++/v1"
```

More about this issue is [here](https://clang-uml.github.io/md_docs_2troubleshooting.html#fatal-error-stddefh-file-not-found)

If this doesn't help, I will need a bit more information about your setup:
- What compiler do you use to actually compile your application?
- How did you generate your `compile_commands.json`?
- Paste the `main.cpp` entry from the `compile_commands.json`
