### ISSUE TITLE
Header file stddef.h not found

### ISSUE THREAD

**Issue by ymanton** [bkryza/clang-uml#64]
Hi, I have a simple test case that fails, giving the following output:

```
[info] [tid 114423] [main.cc:104] Loaded clang-uml config from .clang-uml
[info] [tid 114423] [main.cc:106] Loading compilation database from . directory
[info] [tid 114434] [generator.h:373] Generating diagram test.puml
In file included from /workspaces/test/source.cpp:1:
In file included from /workspaces/test/header.h:4:
/usr/include/stdio.h:33:10: fatal error: 'stddef.h' file not found
#include <stddef.h>
         ^~~~~~~~~~
1 error generated.
Error while processing /workspaces/test/source.cpp.
[error] [tid 114434] [main.cc:189] Diagram test generation failed
```

Test case:
```
test@cba5038ac203:/workspaces/test$ cat header.h 
#include <stdio.h>
test@cba5038ac203:/workspaces/test$ cat source.cpp 
#include "header.h"
test@cba5038ac203:/workspaces/test$ cat compile_commands.json 
[
    {
        "directory": "/workspaces/test/",
        "command": "/usr/bin/g++ -o source.cpp.o -c /workspaces/test/source.cpp",
        "file": "/workspaces/test/source.cpp"
    }
]
test@cba5038ac203:/workspaces/test$ cat .clang-uml
compilation_database_dir: .
output_directory: ./uml-diagrams
diagrams:
  test:
    type: class
    glob:
      - source.cpp
    using_namespace:
      - myproject
    include:
      namespaces:
        - myproject
    plantuml:
      after:
        - 'note left of {{ alias("MyProjectMain") }}: Main class of myproject library.'
```

I'm using the latest package at `ppa:bkryza/clang-uml`:
```
clang-uml 0.2.2
Copyright (C) 2021-2022 Bartek Kryza <bkryza@gmail.com>
Built with LLVM version: 14.0.0
Using LLVM version: Ubuntu clang version 14.0.0-1ubuntu1
```

Distro is Ubuntu 22.04.1 and I have Clang 12 installed if that's relevant.

**Comment by atschwarz** [comment]
Hi, I had the same problem. Here my quick workaround: You can search in `/usr/lib/gcc` for the file `stddef.h` and add the directory to your CPATH variable.

```bash
find /usr/lib/gcc -iname "stddef.h"
# My result: /usr/lib/gcc/x86_64-linux-gnu/9/include/stddef.h

# Calling clang-uml with modified CPATH
CPATH="/usr/lib/gcc/x86_64-linux-gnu/9/include:${CPATH}" clang-uml ...
```

**Comment by bkryza** [comment]
@atschwarz Thanks for sharing your solution!

@ymanton I've been able to reproduce the issue on a clean Jammy image, and the problem is indeed with the lack of paths to appropriate system headers in `compile_commands.json`. I don't know how you generate your compilation database in your real code but if you're using cmake this fixed the problem on Jammy:

```cmake
project (test)

set(CMAKE_EXPORT_COMPILE_COMMANDS ON)
set(CMAKE_CXX_STANDARD_INCLUDE_DIRECTORIES ${CMAKE_CXX_IMPLICIT_INCLUDE_DIRECTORIES})

add_executable (test source.cpp)
```

which produces the following `compile_commands.json` (I've ran cmake in `_build` subdirectory):

```json
[
{
  "directory": "/workspaces/test/_build",
  "command": "/usr/bin/c++  -isystem /usr/include/c++/11 -isystem /usr/include/x86_64-linux-gnu/c++/11 -isystem /usr/include/c++/11/backward -isystem /usr/lib/gcc/x86_64-linux-gnu/11/include -isystem /usr/local/include -isystem /usr/include/x86_64-linux-gnu -isystem /usr/include  -o CMakeFiles/test.dir/source.cpp.o -c /workspaces/test/source.cpp",
  "file": "/workspaces/test/source.cpp"
}
]
```

P.S. `clang-uml` actually crashes after that on this code base because the files are empty - but that's another issue...

**Comment by bkryza** [comment]
@ymanton I did some more digging and found yet another solution:

```bash
apt install clang
```

which among other things installs the LLVM/Clang system headers which are needed by Clang libraries used by `clang-uml` to parse the code, however it does take addition 0.5GB of disk space...

P.S. The crash I mentioned above was actually not due to the empty files but to unresolvable alias in:
```yaml
    plantuml:
      after:
        - 'note left of {{ alias("MyProjectMain") }}: Main class of myproject library.'
 ```
I'll try to fix this bug in next release...

**Comment by ymanton** [comment]
Thanks, installing `clang` (Clang 14), fixes it for me as well. Feel free to close.

I guess we need the same version of Clang that was used to build clang-uml to be installed at runtime. Maybe you can add that as a dependency of your PPA package so that it will be pulled in automatically?
